/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-polkit-agent/dbus/adapter/org.deepin.dde.Polkit1.AuthAgent.xml -a ./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Polkit1.AuthAgentAdaptor -i ./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Polkit1.AuthAgent.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_POLKIT1_AUTHAGENTADAPTOR_H
#define ORG_DEEPIN_DDE_POLKIT1_AUTHAGENTADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Polkit1.AuthAgent.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Polkit1.AuthAgent
 */
class AuthAgentAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Polkit1.AuthAgent")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Polkit1.AuthAgent\">\n"
"    <method name=\"setWIdForAction\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"t\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    AuthAgentAdaptor(QObject *parent);
    virtual ~AuthAgentAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void setWIdForAction(const QString &in0, qulonglong in1);
Q_SIGNALS: // SIGNALS
};

#endif
