/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-polkit-agent/dbus/adapter/org.deepin.dde.Polkit1.AuthAgent.xml -a ./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Polkit1.AuthAgentAdaptor -i ./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Polkit1.AuthAgent.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Polkit1.AuthAgentAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AuthAgentAdaptor
 */

AuthAgentAdaptor::AuthAgentAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AuthAgentAdaptor::~AuthAgentAdaptor()
{
    // destructor
}

void AuthAgentAdaptor::setWIdForAction(const QString &in0, qulonglong in1)
{
    // handle method call org.deepin.dde.Polkit1.AuthAgent.setWIdForAction
    QMetaObject::invokeMethod(parent(), "setWIdForAction", Q_ARG(QString, in0), Q_ARG(qulonglong, in1));
}

