/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-polkit-agent/dbus/org.deepin.dde.Fprintd1.xml -a ./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Fprintd1Adaptor -i ./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Fprintd1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Fprintd1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Fprintd1Adaptor
 */

Fprintd1Adaptor::Fprintd1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Fprintd1Adaptor::~Fprintd1Adaptor()
{
    // destructor
}

QList<QDBusObjectPath> Fprintd1Adaptor::devices() const
{
    // get the value of property Devices
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("Devices"));
}

QDBusObjectPath Fprintd1Adaptor::GetDefaultDevice()
{
    // handle method call org.deepin.dde.Fprintd1.GetDefaultDevice
    QDBusObjectPath out0;
    QMetaObject::invokeMethod(parent(), "GetDefaultDevice", Q_RETURN_ARG(QDBusObjectPath, out0));
    return out0;
}

QList<QDBusObjectPath> Fprintd1Adaptor::GetDevices()
{
    // handle method call org.deepin.dde.Fprintd1.GetDevices
    QList<QDBusObjectPath> out0;
    QMetaObject::invokeMethod(parent(), "GetDevices", Q_RETURN_ARG(QList<QDBusObjectPath>, out0));
    return out0;
}

