/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-polkit-agent/dbus/org.deepin.dde.Fprintd1.Device.xml -a ./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Fprintd1.DeviceAdaptor -i ./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Fprintd1.Device.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_FPRINTD1_DEVICEADAPTOR_H
#define ORG_DEEPIN_DDE_FPRINTD1_DEVICEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Fprintd1.Device.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Fprintd1.Device
 */
class DeviceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Fprintd1.Device")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Fprintd1.Device\">\n"
"    <method name=\"Claim\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"DeleteEnrolledFingers\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"EnrollStart\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"EnrollStop\"/>\n"
"    <method name=\"ListEnrolledFingers\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"    </method>\n"
"    <method name=\"Release\"/>\n"
"    <method name=\"VerifyStart\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"VerifyStop\"/>\n"
"    <signal name=\"EnrollStatus\">\n"
"      <arg type=\"s\"/>\n"
"      <arg type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"VerifyStatus\">\n"
"      <arg type=\"s\"/>\n"
"      <arg type=\"b\"/>\n"
"    </signal>\n"
"    <signal name=\"VerifyFingerSelected\">\n"
"      <arg type=\"s\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    DeviceAdaptor(QObject *parent);
    virtual ~DeviceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Claim(const QString &in0);
    void DeleteEnrolledFingers(const QString &in0);
    void EnrollStart(const QString &in0);
    void EnrollStop();
    QStringList ListEnrolledFingers(const QString &in0);
    void Release();
    void VerifyStart(const QString &in0);
    void VerifyStop();
Q_SIGNALS: // SIGNALS
    void EnrollStatus(const QString &in0, bool in1);
    void VerifyFingerSelected(const QString &in0);
    void VerifyStatus(const QString &in0, bool in1);
};

#endif
