/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-polkit-agent/dbus/org.deepin.dde.Fprintd1.xml -a ./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Fprintd1Adaptor -i ./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Fprintd1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_DDE_FPRINTD1ADAPTOR_H
#define ORG_DEEPIN_DDE_FPRINTD1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-polkit-agent/toolGenerate/qdbusxml2cpp/org.deepin.dde.Fprintd1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.dde.Fprintd1
 */
class Fprintd1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.dde.Fprintd1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.dde.Fprintd1\">\n"
"    <method name=\"GetDefaultDevice\">\n"
"      <arg direction=\"out\" type=\"o\"/>\n"
"    </method>\n"
"    <method name=\"GetDevices\">\n"
"      <arg direction=\"out\" type=\"ao\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"ao\" name=\"Devices\"/>\n"
"  </interface>\n"
        "")
public:
    Fprintd1Adaptor(QObject *parent);
    virtual ~Fprintd1Adaptor();

public: // PROPERTIES
    Q_PROPERTY(QList<QDBusObjectPath> Devices READ devices)
    QList<QDBusObjectPath> devices() const;

public Q_SLOTS: // METHODS
    QDBusObjectPath GetDefaultDevice();
    QList<QDBusObjectPath> GetDevices();
Q_SIGNALS: // SIGNALS
};

#endif
